'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let category='all';
function navigate(){if(location.hash==='#main')return;const key=location.hash.slice(1).split('/')[0]||'commands';const valid=$('#'+key+'.view')?key:'commands';$$('.view').forEach(v=>v.hidden=v.id!==valid);$$('nav a').forEach(a=>{const active=a.hash==='#'+valid;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(valid==='assignments'){const id=location.hash.split('/')[1];if(id)selectAssignment(id,false)}window.scrollTo(0,0)}
function filterCommands(){const q=$('#search').value.trim().toLocaleLowerCase();let count=0;$$('.command-card').forEach(c=>{const ok=(category==='all'||c.dataset.category===category)&&(!q||c.textContent.toLocaleLowerCase().includes(q)||c.dataset.keywords.includes(q));c.hidden=!ok;if(ok)count++});$('#result-count').textContent=`พบ ${count} คำสั่ง`;$('#empty').hidden=count!==0}
function selectAssignment(id,update=true){if(!$('#assignment-'+id))return;$$('.assignment-panel').forEach(p=>p.hidden=p.id!=='assignment-'+id);$$('.assign-button').forEach(b=>{const active=b.dataset.assignment===id;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});if(update)location.hash='assignments/'+id}
$('#search').addEventListener('input',filterCommands);$$('[data-category-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.categoryFilter;$$('[data-category-filter]').forEach(x=>{const a=x===b;x.classList.toggle('active',a);x.setAttribute('aria-pressed',a)});filterCommands()}));$$('.assign-button').forEach(b=>b.addEventListener('click',()=>selectAssignment(b.dataset.assignment)));$('#print').addEventListener('click',()=>window.print());
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,2400)}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;const pre=b.parentElement.querySelector('pre');const text=pre.textContent;try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(text);toast('คัดลอกคำสั่งแล้ว · ตรวจ path และค่าที่ต้องแทนก่อนรัน')}catch{const selection=window.getSelection(),range=document.createRange();range.selectNodeContents(pre);selection.removeAllRanges();selection.addRange(range);toast('เลือกข้อความแล้ว · กด Ctrl+C หรือ ⌘C เพื่อคัดลอก')}});
window.addEventListener('hashchange',navigate);navigate();filterCommands();
